// <auto-generated />
using System;
using AnagoLeaderboard.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnagoLeaderboard.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260812162540_AddressEveryGift")]
    partial class AddressEveryGift
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("AnagoLeaderboard.Models.Results.CardInstance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIcon")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MintedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackClaimId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectPlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PackClaimId");

                    b.HasIndex("SubjectPlayerId");

                    b.HasIndex("PlayerId", "SubjectPlayerId");

                    b.ToTable("CardInstances");
                });

            modelBuilder.Entity("AnagoLeaderboard.Models.Results.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("AnagoLeaderboard.Models.Results.PackClaim", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GiftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GiftId");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasFilter("\"Source\" = 'Icons'");

                    b.HasIndex("PlayerId", "ClaimDate")
                        .IsUnique()
                        .HasFilter("\"Source\" = 'Daily'");

                    b.HasIndex("PlayerId", "GiftId")
                        .IsUnique();

                    b.HasIndex("PlayerId", "Source", "GameId")
                        .IsUnique();

                    b.ToTable("PackClaims");
                });

            modelBuilder.Entity("AnagoLeaderboard.Models.Results.PackGift", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinimumOverall")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PackGifts");
                });

            modelBuilder.Entity("AnagoLeaderboard.Models.Results.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfGames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AnagoLeaderboard.Models.Results.PlayerCollection", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IconsUnlockedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerCollections");
                });

            modelBuilder.Entity("AnagoLeaderboard.Models.Results.CardInstance", b =>
                {
                    b.HasOne("AnagoLeaderboard.Models.Results.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AnagoLeaderboard.Models.Results.PackClaim", null)
                        .WithMany()
                        .HasForeignKey("PackClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnagoLeaderboard.Models.Results.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnagoLeaderboard.Models.Results.Player", null)
                        .WithMany()
                        .HasForeignKey("SubjectPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnagoLeaderboard.Models.Results.Game", b =>
                {
                    b.OwnsOne("AnagoLeaderboard.Models.Results.TeamPerformance", "FirstTeam", b1 =>
                        {
                            b1.Property<string>("GameId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Goals")
                                .HasColumnType("INTEGER");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");

                            b1.OwnsOne("AnagoLeaderboard.Models.Results.PlayerPerformance", "FirstPlayer", b2 =>
                                {
                                    b2.Property<string>("TeamPerformanceGameId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("NewRating")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("OldRating")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("PlayerId")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("TeamPerformanceGameId");

                                    b2.ToTable("Games");

                                    b2.WithOwner()
                                        .HasForeignKey("TeamPerformanceGameId");
                                });

                            b1.OwnsOne("AnagoLeaderboard.Models.Results.PlayerPerformance", "SecondPlayer", b2 =>
                                {
                                    b2.Property<string>("TeamPerformanceGameId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("NewRating")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("OldRating")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("PlayerId")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("TeamPerformanceGameId");

                                    b2.ToTable("Games");

                                    b2.WithOwner()
                                        .HasForeignKey("TeamPerformanceGameId");
                                });

                            b1.Navigation("FirstPlayer")
                                .IsRequired();

                            b1.Navigation("SecondPlayer")
                                .IsRequired();
                        });

                    b.OwnsOne("AnagoLeaderboard.Models.Results.TeamPerformance", "SecondTeam", b1 =>
                        {
                            b1.Property<string>("GameId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Goals")
                                .HasColumnType("INTEGER");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");

                            b1.OwnsOne("AnagoLeaderboard.Models.Results.PlayerPerformance", "FirstPlayer", b2 =>
                                {
                                    b2.Property<string>("TeamPerformanceGameId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("NewRating")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("OldRating")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("PlayerId")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("TeamPerformanceGameId");

                                    b2.ToTable("Games");

                                    b2.WithOwner()
                                        .HasForeignKey("TeamPerformanceGameId");
                                });

                            b1.OwnsOne("AnagoLeaderboard.Models.Results.PlayerPerformance", "SecondPlayer", b2 =>
                                {
                                    b2.Property<string>("TeamPerformanceGameId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("NewRating")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("OldRating")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("PlayerId")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("TeamPerformanceGameId");

                                    b2.ToTable("Games");

                                    b2.WithOwner()
                                        .HasForeignKey("TeamPerformanceGameId");
                                });

                            b1.Navigation("FirstPlayer")
                                .IsRequired();

                            b1.Navigation("SecondPlayer")
                                .IsRequired();
                        });

                    b.Navigation("FirstTeam")
                        .IsRequired();

                    b.Navigation("SecondTeam")
                        .IsRequired();
                });

            modelBuilder.Entity("AnagoLeaderboard.Models.Results.PackClaim", b =>
                {
                    b.HasOne("AnagoLeaderboard.Models.Results.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AnagoLeaderboard.Models.Results.PackGift", null)
                        .WithMany()
                        .HasForeignKey("GiftId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AnagoLeaderboard.Models.Results.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnagoLeaderboard.Models.Results.PackGift", b =>
                {
                    b.HasOne("AnagoLeaderboard.Models.Results.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnagoLeaderboard.Models.Results.PlayerCollection", b =>
                {
                    b.HasOne("AnagoLeaderboard.Models.Results.Player", null)
                        .WithOne()
                        .HasForeignKey("AnagoLeaderboard.Models.Results.PlayerCollection", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
